function subController($scope){
   $scope.plans=[
                {
		        "id": "101",
		        "name": "Occasional Reader",
		        "per_derlivery": "1",
		        "duration": "3",
		        "deliveries": "3",
		        "total_books": "3",
		        "membership_fee": "200",
		        "delivery_charges": "50",
		        "refundable_security": "250",
		        "subscription_fee": "360",
		        "suitable_for": "Individuals, Young Readers",
		        "max_magazines": "1"
		      },
		      {
		        "id": "102",
		        "name": "Occasional Reader",
		        "per_derlivery": "1",
		        "duration": "6",
		        "deliveries": "6",
		        "total_books": "6",
		        "membership_fee": "200",
		        "delivery_charges": "50",
		        "refundable_security": "250",
		        "subscription_fee": "700",
		        "suitable_for": "Individuals, Young Readers",
		        "max_magazines": "2"
		      },
		      {
		        "id": "103",
		        "name": "Occasional Reader",
		        "per_derlivery": "1",
		        "duration": "12",
		        "deliveries": "12",
		        "total_books": "12",
		        "membership_fee": "200",
		        "delivery_charges": "250",
		        "refundable_security": "250",
		        "subscription_fee": "1260",
		        "suitable_for": "Individuals, Young Readers",
		        "max_magazines": "4"
		      },
		      {
		        "id": "104",
		        "name": "Casual Reader",
		        "per_derlivery": "2",
		        "duration": "3",
		        "deliveries": "3",
		        "total_books": "6",
		        "membership_fee": "200",
		        "delivery_charges": "50",
		        "refundable_security": "500",
		        "subscription_fee": "690",
		        "suitable_for": "Individuals, Young Readers",
		        "max_magazines": "1"
		      },
		      {
		        "id": "105",
		        "name": "Casual Reader",
		        "per_derlivery": "2",
		        "duration": "6",
		        "deliveries": "6",
		        "total_books": "12",
		        "membership_fee": "200",
		        "delivery_charges": "50",
		        "refundable_security": "500",
		        "subscription_fee": "1310",
		        "suitable_for": "Individuals, Young Readers",
		        "max_magazines": "2"
		      },
		      {
		        "id": "106",
		        "name": "Casual Reader",
		        "per_derlivery": "2",
		        "duration": "12",
		        "deliveries": "12",
		        "total_books": "24",
		        "membership_fee": "200",
		        "delivery_charges": "50",
		        "refundable_security": "500",
		        "subscription_fee": "2480",
		        "suitable_for": "Individuals, Young Readers",
		        "max_magazines": "4"
		      },
		      {
		        "id": "107",
		        "name": "Regular Reader",
		        "per_derlivery": "3",
		        "duration": "3",
		        "deliveries": "3",
		        "total_books": "9",
		        "membership_fee": "200",
		        "delivery_charges": "50",
		        "refundable_security": "750",
		        "subscription_fee": "990",
		        "suitable_for": "Book Lovers, Regular Readers",
		        "max_magazines": "2"
		      },
		      {
		        "id": "108",
		        "name": "Regular Reader",
		        "per_derlivery": "3",
		        "duration": "6",
		        "deliveries": "6",
		        "total_books": "18",
		        "membership_fee": "200",
		        "delivery_charges": "50",
		        "refundable_security": "750",
		        "subscription_fee": "1880",
		        "suitable_for": "Book Lovers, Regular Readers",
		        "max_magazines": "4"
		      },
		      {
		        "id": "109",
		        "name": "Regular Reader",
		        "per_derlivery": "3",
		        "duration": "12",
		        "deliveries": "12",
		        "total_books": "36",
		        "membership_fee": "200",
		        "refundable_security": "750",
		        "subscription_fee": "3560",
		        "suitable_for": "Book Lovers, Regular Readers",
		        "max_magazines": "8"
		      },
		      {
		        "id": "110",
		        "name": "Fervent Reader",
		        "per_derlivery": "6",
		        "duration": "3",
		        "deliveries": "3",
		        "total_books": "18",
		        "membership_fee": "200",
		        "delivery_charges": "100",
		        "refundable_security": "1500",
		        "subscription_fee": "1800",
		        "suitable_for": "Book worms , Families",
		        "max_magazines": "4"
		      },
		      {
		        "id": "111",
		        "name": "Fervent Reader",
		        "per_derlivery": "6",
		        "duration": "6",
		        "deliveries": "6",
		        "total_books": "36",
		        "membership_fee": "200",
		        "delivery_charges": "100",
		        "refundable_security": "1500",
		        "subscription_fee": "3420",
		        "suitable_for": "Book worms , Families",
		        "max_magazines": "8"
		      },
		      {
		        "id": "112",
		        "name": "Fervent Reader",
		        "per_derlivery": "6",
		        "duration": "12",
		        "deliveries": "12",
		        "total_books": "72",
		        "membership_fee": "200",
		        "delivery_charges": "100",
		        "refundable_security": "1500",
		        "subscription_fee": "6480",
		        "suitable_for": "Book worms , Families",
		        "max_magazines": "12"
		      }
		    ];		  
   };